version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: my-postgres-apdopet
    networks:
      - my-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lasBr01
      POSTGRES_DB: adopet_db
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin-apdopet
    networks:
      - my-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres

networks:
  my-network:

volumes:
  postgres_data:
